[package]
name = "auxmos"
version = "0.1.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
equalization = []
monstermos = ["equalization"]
putnamos = ["equalization"]
reaction_hooks = []
plasma_fire_hook = ["reaction_hooks"]
trit_fire_hook = ["reaction_hooks"]
fusion_hook = ["reaction_hooks"]
generic_fire_hook = ["reaction_hooks"]
all_reaction_hooks = ["fusion_hook", "trit_fire_hook", "plasma_fire_hook", "generic_fire_hook"]
explosive_decompression = ["monstermos"]
putnamos_decompression = ["putnamos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/willox/auxtools"}
auxcallback = { git = "https://github.com/Putnam3145/auxcallback" }
itertools = "0.10.1"
rayon = "1.5.0"
float-ord = "0.2.0"
crossbeam = "0.8.0"
flume = "0.10.5"
coarsetime = "0.1.16"
parking_lot = "0.11.1"
fxhash = "0.2.1"
packed_simd_2 = "0.3.5"
lindel = "0.1.1"

[dependencies.dashmap]
version = "4.0.2"
features = ["raw-api"]

[dependencies.tinyvec]
version = "1.1.0"
features = ["rustc_1_40", "alloc"]

[profile.release]
lto = 'thin'
debug = true
panic = 'abort'
