[package]
name = "auxmos"
version = "0.1.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
equalization = []
monstermos = ["equalization"]
putnamos = ["equalization"]
reaction_hooking = []
plasma_fire_hook = ["reaction_hooking"]
trit_fire_hook = ["reaction_hooking"]
fusion_hook = ["reaction_hooking"]
all_reaction_hooks = ["fusion_hook", "trit_fire_hook", "plasma_fire_hook"]
explosive_decompression = ["monstermos"]
putnamos_decompression = ["putnamos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/willox/auxtools"}
auxcallback = { git = "https://github.com/Putnam3145/auxcallback" }
lazy_static = "1.4.0"
itertools = "0.9.0"
rayon = "1.5.0"
float-ord = "0.2.0"
crossbeam = "0.8.0"
flume = "0.9.1"
coarsetime = "0.1.16"
parking_lot = "0.11.1"
bitvec = "0.22.3"

[dependencies.dashmap]
version = "4.0.2"
features = ["raw-api"]

[dependencies.tinyvec]
version = "1.1.0"
features = ["rustc_1_40", "alloc"]

[profile.release]
opt-level = 3
lto = 'thin'
codegen-units = 1
incremental = true
debug = true
panic = "abort"

[profile.dev]
panic = "abort"
